<?php

/*composer cmd : 
    composer config minimum-stability dev
    composer require xiippy/posecomsdk
    package url : https://packagist.org/packages/xiippy/posecomsdk
*/


require_once __DIR__ . '/vendor/autoload.php';
require 'IndexPHPInitializer.php';


use \Xiippy\POSeComSDK\Light\XiippySDKBridgeApiClient\Constants;
use \Xiippy\POSeComSDK\Light\XiippySDKBridgeApiClient;
use \Xiippy\POSeComSDK\Light\Models\PaymentProcessingRequest;
use \Xiippy\POSeComSDK\Light\Models\PaymentRecordCustomer;
use \Xiippy\POSeComSDK\Light\Models\IssuerStatementRecord;
use \Xiippy\POSeComSDK\Light\Models\PaymentRecordCustomerAddress;
use \Xiippy\POSeComSDK\Light\Models\StatementItem;
use Xiippy\IndexPHPInitializer;



$XiippyFrameUrl = null;
$ErrorText = null;

try {
    $XiippyFrameUrl = IndexPHPInitializer::InitiatePaymentNGetiFrameUrl();
} catch (Exception $e) {
    $ErrorText = $e->getMessage();
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>XiippySDKBridgeSamplePHPApp</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/site.css" />
</head>

<body>



    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/">XiippySDKBridgeSamplePhpApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">

            <div class="text-center">
                <h1 class="display-4">Welcome</h1>
                <p>This is a simple payment form which show how Xiippy's basic data-rich payments can be added to a
                    web-based e-commerce server with around 100 lines of code'.</p>



                <?php if (!is_null($ErrorText)) { ?>
                    <div class="alert alert-danger alert-dismissible fade show text-break" role="alert">
                        <p><strong>Error</strong></p>
                        <p> <?= $ErrorText ?></p>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true"></span>
                        </button>
                    </div>

                <?php } ?>


                <div id="frameContainer" style="width:100%; margin:0 auto 0 auto; min-height:300"></div>
                <div id="diverror" style="width:100%; margin:0 auto 0 auto;"></div>


                <script src="https://cdn.xiippy.ai/PaymentScripts/app.XiippyFrameSDK.bundle.js"></script>
                <script>
                    function initXiippyFrameSDK() {

                        // initialize parameters
                        var FrameContainerID = 'frameContainer';
                        // this parameter is generated by Xiippy's server-side SDK and has to be set from the server
                        var Url = '<?= $XiippyFrameUrl ?>';
                        var sdkInstance = new XiippyFrameSDK.XiippyFrameSDK(FrameContainerID, Url);

                        // listen for events
                        sdkInstance.on('PaymentProcessed', (eventArgs) => {
                            // you need to implement payment success logic here
                            console.log('PaymentProcessed event was fired!', eventArgs);
                        });

                        sdkInstance.on('PaymentError', (eventArgs) => {
                            // you need to implement retrying or error handling logic here!
                            console.log('PaymentError event was fired!', eventArgs);
                            document.getElementById('diverror').innerText = eventArgs?.eventArgs?.error?.message;

                        });

                    }

                    // initialize the SDK upon page load
                    window.addEventListener("load", () => initXiippyFrameSDK(), false);
                </script>

            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - XiippySDKBridgeSamplePhpApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="lib/jquery/dist/jquery.min.js"></script>
    <script src="lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/site.js" asp-append-version="true"></script>

</body>

</html>